dnaStrand = 'GGCAGTTCTACGCCTGAGATAGAGTCTCATCGAGACTCAGAGATACAAACGCTCTAAAGACGTACTTAGGAGAGTGCGTTGAAGTTAGACTAGGCGCAGACGGAGGTAAAAGATGGCTGCACCCAGCATGTTCGTTTATATGCCCTGATTAGTGTGTTAATATAGGTCTTTATTTCGCATATACACACTGTGTGGTAACATGGCTCTAATCAGATATCTGTGTCAGCCCCGTTTAGTAAGTAATCAGCCTTTCACCATAGTACATGGTTGGAATACGCGCCATGAGACCATACATCATGATCAATGATGCATAAAATCATCCGAGGTGTAAAATTAGAGTACCTGTAGATGGCGTGCCGCCCAGGCAAAAGTATCAACGCACGTGACATGCTAGCGGAGGTCGCAGCTCACCTTTAACTGGGATATTACTTAGTAGGTTTGGCCGCCTCCTAAGTCGTTAAGTGGGTGCTACTACCACGTATATAAGCTTGCTGAAATTTCTTGTTGTCAGTGCTGCACATGGGGGCTTCGACACGTGCCGACAATGCCGTGTTGTGATTACAACAGTTCAATAATTATATTTAGTCCATTTCGCCTAGCTGCTTCGAGTAGGACTTATATAGCCGGTGCACGCAAGGCTCGGGCAGGACGTAAAGTATATTATCACATATAGCATACGTTTCACTTGACACACCGGCCGCTATCACCAACTGGGGCACGGGTCAGCCAACAATGCGATTTGCGCCATCCCTCATGCGGTACTTTGGACGTATGAGGGTACAAATAAAGAACCGGAAATATTCAGTGGTGGAAGATTTGAGTTGCGGCTACTCCAGGGTGTTTACCGTATTCGACTAAAGATAACCTGTAAATAGTAGCTGGTATAACTTCCAGCTTAAAGCCATCTATTAATACAACTATGGACATGACCCGCACTTAGGGTCAGGTTCAGAGGTACGTCATGATTCGCAGCGGGTC'
ntBuckets = [0, 0, 0, 0]

for i in range(0, len(dnaStrand)):
	if dnaStrand[i] == 'A':
		ntBuckets[0] = ntBuckets[0] + 1
	elif dnaStrand[i] == 'C':
		ntBuckets[1] = ntBuckets[1] + 1
	elif dnaStrand[i] == 'G':
		ntBuckets[2] = ntBuckets[2] + 1
	elif dnaStrand[i] == 'T':
		ntBuckets[3] = ntBuckets[3] + 1

outputString = str(ntBuckets[0]) + ' ' + str(ntBuckets[1]) + ' ' + str(ntBuckets[2]) + ' ' + str(ntBuckets[3])

print(outputString)
